# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Общая примерная стоимость', max_digits=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество входных токенов'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_output_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество выходных токенов'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество токенов'),
        ),
        migrations.AddField(
            model_name='message',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Примерная стоимость в долларах', max_digits=10),
        ),
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Количество токенов на входе'),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Количество токенов в ответе'),
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество токенов'),
        ),
    ]
