# Generated by Django 5.2.7 on 2025-10-14 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название агента', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание агента')),
                ('model', models.CharField(help_text='Модель ИИ', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Температура')),
                ('top_p', models.FloatField(default=1.0, help_text='Top P')),
                ('system_prompt', models.TextField(blank=True, help_text='Системный промпт')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли агент')),
                ('current_session', models.ForeignKey(blank=True, help_text='Текущая активная сессия агента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
