# Generated by Django 5.2.3 on 2025-10-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4000, help_text='Максимальное количество токенов'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
