# Generated by Django 5.2.3 on 2025-10-18 15:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_agent_max_tokens_chatsession_max_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название функции', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание функции')),
                ('json_definition', models.JSONField(help_text='JSON определение функции в формате OpenAI')),
                ('python_code', models.TextField(help_text='Python код функции')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли функция')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='Python функции, доступные агенту', related_name='agents', to='chat.pythonfunction'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='Python функции, доступные в сессии', related_name='chat_sessions', to='chat.pythonfunction'),
        ),
    ]
