# Generated by Django 5.2.7 on 2025-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_pythonfunction_agent_functions_chatsession_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='web_search',
            field=models.BooleanField(default=False, help_text='Включен ли поиск в интернете'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='web_search',
            field=models.BooleanField(default=False, help_text='Включен ли поиск в интернете'),
        ),
    ]
